<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>Builder.Tests</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Core\ApolloIQ.Core\ApolloIQ.Core.csproj" />
        <ProjectReference Include="..\Builder.Core\Builder.Core.csproj" />
        <ProjectReference Include="..\Builder.Persistence\Builder.Persistence.csproj" />
        <ProjectReference Include="..\Builder.Backend\Builder.Backend.csproj" />
        <ProjectReference Include="..\Builder.Logic\Builder.Logic.csproj" />
        <ProjectReference Include="..\Builder.Simulator\Builder.Simulator.csproj" />
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    <ItemGroup>
        <None Include="Fixtures\**\*.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
      <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="xunit.v3" Version="4.0.1" />
    </ItemGroup>
</Project>
