<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>Builder.Design</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Builder.Core\Builder.Core.csproj"/>
        <ProjectReference Include="..\Builder.Logic\Builder.Logic.csproj"/>
        <ProjectReference Include="..\Builder.Persistence\Builder.Persistence.csproj"/>
    </ItemGroup>
</Project>
